---
- name: Build and Deploy todolist-api 
  hosts: app
  vars:
    ci_cd_namespace: deven-ci-cd
    dev_namespace: deven-dev
    test_namespace: deven-test
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier